### PR TITLE
create DQN.md

### PR DESCRIPTION
**Pull request by annaivanytska**

### CODE REVIEW

**Review by CISonIT — CHANGES_REQUESTED** [review]
at least smthing ...  but i won't merge it to main, I will wait for better documentation, but commit is noted

**Review by D-Mielewczyk — CHANGES_REQUESTED** [review]
just download those images and put the into assets please - they can disappear in the future - credit the author if necessery

**Review by CISonIT — APPROVED** [review]

**Comment by CISonIT** [comment]
@D-Mielewczyk is right, correct please

**Review by D-Mielewczyk — APPROVED** [review]
If you have tested this on a local host - please merge.

**Pull request merged**
